#!/usr/bin/env bash
# shellcheck disable=SC2086
domain=$1
subdomain=$2
check_subdomain() {
   local sub=$1
   result=$(dig "$sub.$domain")


   record_type=$(echo "$result" | awk '/ANSWER SECTION:/ {getline; print $4}')

   
   destination=$(echo "$result" | awk '/ANSWER SECTION:/ {getline; print $5}')


   echo "The subdomain $sub is a $record_type record and points to $destination"
}
#checking whether the user typed the subdomain or no
if [ -z "$subdomain" ]; then
	check_subdomain "www"
	check_subdomain "lb-01"
	check_subdomain "web-01"
	check_subdomain "web-02"
else
	check_subdomain "$subdomain"
fi
